### ISSUE TITLE
Nesting issue with dictionary>dictionary

### ISSUE THREAD

**Issue by erkekin** [AykutSarac/jsonvisio.com#50] opened 2022-06-09 10:12 UTC
<img width="1091" alt="Screenshot 2022-06-09 at 11 10 23 am" src="https://user-images.githubusercontent.com/701481/172823204-e7723b2e-7a42-4581-9c0e-ddf494ebc23e.png">

I think the empty box in the middle should go

for ease of reference 
```json
 "stepUpAuthVerification": {
      "stepUpDirective": {
        "actionId": "GLOS01",
        "additionalVerificationRequired": true,
        "useNativeStepUp": true
      }
    }
```

**Comment by AykutSarac** [comment] 2022-06-09 18:07
Duplicate of #27.

**Closed by AykutSarac** 2022-06-09 18:07 UTC
