### ISSUE TITLE
Rendering issue on iPad

### ISSUE THREAD

**Issue by grempe** [AykutSarac/jsonvisio.com#7] opened 2022-03-18 14:35 UTC
See attached screenshot. The nodes render without any text (which seems to be accumulated in the top left corner).

![IMG_983D78108C9D-1](https://user-images.githubusercontent.com/117/159022654-99f0befd-23eb-4d9f-b879-acdefef8ff8f.jpeg)

**Comment by AykutSarac** [comment] 2022-03-19 13:07
I have pushed a fix for this (615de0c157b4f5f5bbdc9a1b306c5a4e75186052). Unfortunately I'm unable to reproduce this on my end, can you please check it again and confirm if it has solved the issue?

**Comment by grempe** [comment] 2022-03-19 13:19
Sorry, no change yet when viewing on a different iPad (so no chance of cache issue)

**Comment by grempe** [comment] 2022-03-20 01:50
Now its looking good. 👍🏻

![image](https://user-images.githubusercontent.com/117/159144611-48c7e116-ca69-4964-9a92-8bd3a0c4c602.png)

**Comment by AykutSarac** [comment] 2022-03-20 09:23
Glad it has been resolved now, thanks for confirming!

**Closed by AykutSarac** 2022-03-20 09:23 UTC
Labels: bug
